Flag sets
splitio/javascript-client pull request #771
Opened 2023-10-24 19:13 UTC by emmaz90

# JS SDK

## What did you accomplish?

## How do we test the changes introduced in this PR?

## Extra Notes

2023-10-25 04:23 UTC, sennhann29 approved these changes

2023-10-26 17:32 UTC, EmilianoSanchez requested changes
Small comment to check before merging. 
Also add the changelog entry for the changes you did.

2023-10-26 17:32 UTC, EmilianoSanchez commented on .github/workflows/ci-cd.yml
> +        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/sdks-7437' || github.ref == 'refs/heads/master') }}
Rollback this change

2023-11-01 14:17 UTC, EmilianoSanchez requested changes

2023-11-01 14:17 UTC, EmilianoSanchez commented on types/splitio.d.ts
> +  type SplitFilterType = 'bySet' | 'byName' | 'byPrefix';
missing the sets property in SplitView type.
Check https://github.com/splitio/react-native-client/pull/71

2023-12-04 16:12 UTC, EmilianoSanchez approved these changes

2023-12-04 16:28 UTC, merged